# Espacio vecorial distribucional

In [1]:
import numpy as np

In [2]:
sentences = ['Juan come sushi','Pedro come unos tacos','Juan prepara tacos','Pedro prepara sushi']

In [3]:
from collections import defaultdict

def vocab():
    dicc = defaultdict()
    dicc.default_factory = lambda: len(dicc)
    return dicc

def BoW(corpus,vocab):
    for w in corpus:
        yield[vocab[w_i] for w_i in w.split()]
        
words = vocab()
BagOfWords = list(BoW(sentences,words))

In [4]:
print BagOfWords

[[0, 1, 2], [3, 1, 4, 5], [0, 6, 5], [3, 6, 2]]


In [5]:
print words["Juan"]

0


In [6]:
print words["Pedro"]

3


In [8]:
A = np.zeros((len(words),len(words)))
print A.shape

(7L, 7L)


In [9]:
for w1 in words:
    for w2 in words:
        cooc = 0
        for context in BagOfWords:
            if words[w1] in context and words[w2] in context and w1 != w2:
                cooc += 1
        A[words[w1],words[w2]] = cooc
    
print A

[[ 0.  1.  1.  0.  0.  1.  1.]
 [ 1.  0.  1.  1.  1.  1.  0.]
 [ 1.  1.  0.  1.  0.  0.  1.]
 [ 0.  1.  1.  0.  1.  1.  1.]
 [ 0.  1.  0.  1.  0.  1.  0.]
 [ 1.  1.  0.  1.  1.  0.  1.]
 [ 1.  0.  1.  1.  0.  1.  0.]]


In [11]:
print A[words["Juan"]]

[ 0.  1.  1.  0.  0.  1.  1.]
