# Modelos Ocultos de Markov

In [1]:
from __future__ import division
from csv import reader
from collections import Counter, defaultdict
import numpy as np
from pickle import dump

In [2]:
doc = list(reader(open('corpusHMM2.csv','r'), delimiter=','))
print doc[2]

['la', 'DA']


In [3]:
S = []
O = []
S_f = Counter()
O_f = Counter()
for item in doc:
        tag = item[1]
        token = item[0]
        S_f[tag] += 1
        O_f[token] += 1
        S.append(tag)
        O.append((token,tag))

In [4]:
def voc():
    dict = defaultdict()
    dict.default_factory = lambda: len(dict)
    return dict

def get_ids(C,dict):
    yield [dict[w] for w in C]
    
S_v = voc()
S_num = list(get_ids(S,S_v))

In [5]:
n = len(S_v)

A = np.zeros((n,n))

In [6]:
def pr (x, cond, N, l=1):
    return (x+l) / (cond + l*N)	

In [7]:
chains = Counter(zip(S, S[1:]))
for x in S:
    for y in S:
        f_conj = chains[(x,y)]
        A[S_v[y],S_v[x]] = pr(f_conj, S_f[y],n)
    
print A

[[ 0.1         0.1         0.1         0.2         0.2         0.2       ]
 [ 0.28571429  0.14285714  0.14285714  0.14285714  0.14285714  0.14285714]
 [ 0.14285714  0.28571429  0.14285714  0.14285714  0.14285714  0.14285714]
 [ 0.25        0.125       0.25        0.125       0.125       0.125     ]
 [ 0.14285714  0.14285714  0.14285714  0.28571429  0.14285714  0.14285714]
 [ 0.33333333  0.11111111  0.11111111  0.11111111  0.11111111  0.22222222]]


In [8]:
print A.sum(1)

[ 0.9  1.   1.   1.   1.   1. ]


In [ ]:
f = open('HMM.p','w')
HMM = [A,dict(S_v),dict(O_v)]
dump(HMM,f)

In [ ]:
from pickle import load

A,S,O = load(open('HMM.p','r'))