# Algoritmo de K-medias

In [20]:
%matplotlib inline
import numpy as np
from collections import defaultdict

sentences = ['el gato juega con el perro', 'el carro atropeya al perro', 'el carro atropeya al gato']

def vocab():
    dicc = defaultdict()
    dicc.default_factory = lambda: len(dicc)
    return dicc

def BoW(corpus,vocab):
    for w in corpus:
        yield[vocab[w_i] for w_i in w.split()]
        
words = vocab()
BagOfWords = list(BoW(sentences,words))

A = np.zeros((len(words),len(words)))
for w1 in words:
    for w2 in words:
        cooc = 0
        for context in BagOfWords:
            if words[w1] in context and words[w2] in context and w1 != w2:
                cooc += 1
        A[words[w1],words[w2]] = cooc
    
print A

[[ 0.  2.  1.  1.  2.  2.  2.  2.]
 [ 2.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  0.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  1.  0.  0.  0.]
 [ 2.  1.  1.  1.  0.  1.  1.  1.]
 [ 2.  1.  0.  0.  1.  0.  2.  2.]
 [ 2.  1.  0.  0.  1.  2.  0.  2.]
 [ 2.  1.  0.  0.  1.  2.  2.  0.]]


In [21]:
def eucl(x,y):
    return np.linalg.norm(x-y)

print eucl(A[words['gato']],A[words['perro']])

1.41421356237


In [22]:
def centroids(X, cents, k):
    for cluster in range(0, k):
        cents.append(X[np.random.randint(0, len(X), size=1)].flatten().tolist())
 
    return cents

k = 2
centroides = []
print centroids(A,centroides,k)

[[1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0], [2.0, 1.0, 0.0, 0.0, 1.0, 2.0, 0.0, 2.0]]


In [23]:
def min_dist(X, centroids):
    C = [[] for i in range(k)]
    for x in X:
        mu_index = min( [(i[0], eucl(A[words[x]],centroids[i[0]])) for i in enumerate(centroids)], key=lambda t:t[1] )[0]
        try:
            C[mu_index].append(x)
        except KeyError:
            C[mu_index] = [x]
        
    for cluster in C:
        if not cluster:
            cluster.append(X[np.random.randint(0, len(X), size=1)].flatten().tolist())
 
    return C



C = min_dist(words, centroides)

for c in C:
    print c

['juega', 'gato', 'perro', 'con']
['el', 'al', 'carro', 'atropeya']


In [24]:
centroides_n = [[] for i in range(k)]

while centroides != centroides_n:
    clusts = min_dist(words, centroides)
    
    i = 0
    for c in C:
        centroides_n[i] = centroides[i]
        mean = np.zeros(len(words))
        for point in c:
            mean += (1./len(c))*A[words[point]]
        centroides[i] = list(mean)
        i += 1
print clusts

[['juega', 'gato', 'perro', 'con'], ['el', 'al', 'carro', 'atropeya']]
